### ISSUE TITLE
struct variables have an arbitrarily compiler-determined name

### ISSUE THREAD

**Issue by miraleung** [miraleung/tressa#15]
... unlike primitive locals, which (in C) are identified with the same label in IR as in the source code. This makes detecting such locals / arguments in the targeted function difficult.

**Comment by bestchai** [comment]
Here's the relevant soverflow question:
http://stackoverflow.com/questions/4918001/how-to-preserve-struct-member-identifiers-when-compiling-to-llvm-ir-with-clang

And another one:
http://stackoverflow.com/questions/17409216/llvm-how-to-access-to-struct-fields-based-on-their-names

Looks like this is possible if you compile with debug info, but not otherwise..

**Comment by miraleung** [comment]
This will be really useful for getting struct fields. Will also need to get the name of the struct-typed variable in a function; for instance, `struct node *some_node;` is compiled to have some arbitrary name in the IR.

**Comment by miraleung** [comment]
Closing; turned out to be caused by compiler optimization flags.
